### ISSUE TITLE
Please remove binary files and add code

### ISSUE THREAD

**Issue by pcav** [huginexpert/HUGIN-QGIS#1]

**Comment by pcav** [comment]
e.g. zipfile. Proper code repo should be set up.
Thanks.

**Comment by huginexpert** [comment]
Paolo it seems your first comment is accidentally left blank.

Can you please repeat the issue?

**Comment by pcav** [comment]
Sorry, subject accidentally cancelled.

**Comment by huginexpert** [comment]
Ah ok.
I removed the zip-file, the right place to put it was under githubs releases feature.

The plugin source-code is the single python file HUGIN_raster_belief_update.py

**Comment by huginexpert** [comment]
its a processing script turned into a plugin by following the recipe found in the qgis documentation
https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/processing.html#id2

**Comment by pcav** [comment]
Thanks, now published. Better also replace the documentation, from pdf to rst, and autogenerate the pdf. See other plugins or ask qgis-dev Mailing List for details.
Thanks.
